security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api_login:
            pattern: ^/api/auth
            stateless: true
            json_login:
                check_path: /api/auth/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        # API маршруты защищены через JWT
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~
        api_register:
            pattern: ^/api/register
            security: false

    access_control:
        - { path: '^/api/auth', roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: '^/api/login', roles: PUBLIC_ACCESS }
        - { path: '^/api/docs', roles: PUBLIC_ACCESS }
        - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/upload, roles: IS_AUTHENTICATED_FULLY }
