controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/auth/login_check
    methods: [POST]
upload_file:
    path: /api/upload
    controller: App\Controller\FileUploadController::upload
    methods: [POST]
news_create:
    path: /api/news
    controller: App\Controller\NewsController::create
    methods: [POST]
news_delete:
    path: /api/news/{id}
    controller: App\Controller\NewsController::delete
    methods: [DELETE]
news_list:
    path: /api/news
    controller: App\Controller\NewsController::list
    methods: [GET]